"""fixed bug

Revision ID: 00244fc746c3
Revises: 8d1b81672c3e
Create Date: 2026-05-19 17:22:26.859024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00244fc746c3'
down_revision: Union[str, Sequence[str], None] = '8d1b81672c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('project_comment_votes_comment_id_fkey'), 'project_comment_votes', type_='foreignkey')
    op.drop_constraint(op.f('project_comment_votes_user_id_fkey'), 'project_comment_votes', type_='foreignkey')
    op.create_foreign_key(None, 'project_comment_votes', 'project_comments', ['comment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_comment_votes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_comments_user_id_fkey'), 'project_comments', type_='foreignkey')
    op.drop_constraint(op.f('project_comments_project_id_fkey'), 'project_comments', type_='foreignkey')
    op.create_foreign_key(None, 'project_comments', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_stars_user_id_fkey'), 'project_stars', type_='foreignkey')
    op.drop_constraint(op.f('project_stars_project_id_fkey'), 'project_stars', type_='foreignkey')
    op.create_foreign_key(None, 'project_stars', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_stars', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('projects', sa.Column('demo_video_url', sa.Text(), nullable=True))
    op.drop_constraint(op.f('projects_user_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_user_id_fkey'), 'projects', 'users', ['user_id'], ['id'])
    op.drop_column('projects', 'demo_video_url')
    op.drop_constraint(None, 'project_stars', type_='foreignkey')
    op.drop_constraint(None, 'project_stars', type_='foreignkey')
    op.create_foreign_key(op.f('project_stars_project_id_fkey'), 'project_stars', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('project_stars_user_id_fkey'), 'project_stars', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'project_comments', type_='foreignkey')
    op.drop_constraint(None, 'project_comments', type_='foreignkey')
    op.create_foreign_key(op.f('project_comments_project_id_fkey'), 'project_comments', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('project_comments_user_id_fkey'), 'project_comments', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'project_comment_votes', type_='foreignkey')
    op.drop_constraint(None, 'project_comment_votes', type_='foreignkey')
    op.create_foreign_key(op.f('project_comment_votes_user_id_fkey'), 'project_comment_votes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('project_comment_votes_comment_id_fkey'), 'project_comment_votes', 'project_comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###
