"""Add bookmarks and previous fix

Revision ID: 18de52d74d24
Revises: fa2514a1f273
Create Date: 2026-05-29 21:58:11.179600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18de52d74d24'
down_revision: Union[str, Sequence[str], None] = 'fa2514a1f273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_status', sa.Text(), nullable=True),
    sa.Column('current_goal', sa.Text(), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('github_url', sa.Text(), nullable=True),
    sa.Column('live_url', sa.Text(), nullable=True),
    sa.Column('demo_video_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('gallery_urls', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('views_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('journal_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'paused', 'completed', 'abandoned')", name='check_live_project_status'),
    sa.CheckConstraint('progress_percentage BETWEEN 0 AND 100', name='check_live_project_progress_percentage'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'slug', name='unique_user_live_project_slug')
    )
    op.create_index('ix_live_projects_public_feed', 'live_projects', ['created_at'], unique=False, postgresql_where=sa.text('is_public = true'))
    op.create_index(op.f('ix_live_projects_user_id'), 'live_projects', ['user_id'], unique=False)
    op.create_index('ix_live_projects_user_id_created_at', 'live_projects', ['user_id', 'created_at'], unique=False)
    op.create_table('live_project_journals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('live_project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('entry_type', sa.String(length=50), server_default='progress', nullable=False),
    sa.Column('media_urls', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('code_snippets', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('problem_solutions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('likes_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comments_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            entry_type IN (\n                'progress',\n                'milestone',\n                'bugfix',\n                'deployment',\n                'architecture',\n                'announcement',\n                'failure'\n            )\n            ", name='check_live_project_journal_type'),
    sa.CheckConstraint('progress_percentage IS NULL OR progress_percentage BETWEEN 0 AND 100', name='check_live_project_journal_progress_percentage'),
    sa.ForeignKeyConstraint(['live_project_id'], ['live_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_project_journals_live_project_id'), 'live_project_journals', ['live_project_id'], unique=False)
    op.create_index('ix_live_project_journals_project_created_at', 'live_project_journals', ['live_project_id', 'created_at'], unique=False)
    op.create_index('ix_live_project_journals_user_created_at', 'live_project_journals', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_live_project_journals_user_id'), 'live_project_journals', ['user_id'], unique=False)
    op.create_table('live_project_journal_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('journal_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('likes_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_edited', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['live_project_journals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['live_project_journal_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_live_project_journal_comments_journal_created_at', 'live_project_journal_comments', ['journal_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_live_project_journal_comments_journal_id'), 'live_project_journal_comments', ['journal_id'], unique=False)
    op.create_index('ix_live_project_journal_comments_parent_id', 'live_project_journal_comments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_live_project_journal_comments_user_id'), 'live_project_journal_comments', ['user_id'], unique=False)
    op.create_table('live_project_journal_likes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('journal_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['live_project_journals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'journal_id', name='unique_live_project_journal_like')
    )
    op.create_index('ix_live_project_journal_likes_journal_id', 'live_project_journal_likes', ['journal_id'], unique=False)
    op.create_index('ix_live_project_journal_likes_user_id', 'live_project_journal_likes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_live_project_journal_likes_user_id', table_name='live_project_journal_likes')
    op.drop_index('ix_live_project_journal_likes_journal_id', table_name='live_project_journal_likes')
    op.drop_table('live_project_journal_likes')
    op.drop_index(op.f('ix_live_project_journal_comments_user_id'), table_name='live_project_journal_comments')
    op.drop_index('ix_live_project_journal_comments_parent_id', table_name='live_project_journal_comments')
    op.drop_index(op.f('ix_live_project_journal_comments_journal_id'), table_name='live_project_journal_comments')
    op.drop_index('ix_live_project_journal_comments_journal_created_at', table_name='live_project_journal_comments')
    op.drop_table('live_project_journal_comments')
    op.drop_index(op.f('ix_live_project_journals_user_id'), table_name='live_project_journals')
    op.drop_index('ix_live_project_journals_user_created_at', table_name='live_project_journals')
    op.drop_index('ix_live_project_journals_project_created_at', table_name='live_project_journals')
    op.drop_index(op.f('ix_live_project_journals_live_project_id'), table_name='live_project_journals')
    op.drop_table('live_project_journals')
    op.drop_index('ix_live_projects_user_id_created_at', table_name='live_projects')
    op.drop_index(op.f('ix_live_projects_user_id'), table_name='live_projects')
    op.drop_index('ix_live_projects_public_feed', table_name='live_projects', postgresql_where=sa.text('is_public = true'))
    op.drop_table('live_projects')
    # ### end Alembic commands ###
