"""add feed events

Revision ID: 2797d7a9fb2a
Revises: 3c3bac90387e
Create Date: 2026-06-02 18:07:39.189085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2797d7a9fb2a'
down_revision: Union[str, Sequence[str], None] = '3c3bac90387e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('live_project_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('likes_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comments_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['live_project_id'], ['live_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feed_events_created_at', 'feed_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_feed_events_live_project_id'), 'feed_events', ['live_project_id'], unique=False)
    op.create_index('ix_feed_events_project_created_at', 'feed_events', ['live_project_id', 'created_at'], unique=False)
    op.create_index('ix_feed_events_user_created_at', 'feed_events', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_feed_events_user_id'), 'feed_events', ['user_id'], unique=False)
    op.drop_constraint(op.f('unique_user_stack'), 'user_stack_stats', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('unique_user_stack'), 'user_stack_stats', ['user_id', 'stack_name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_feed_events_user_id'), table_name='feed_events')
    op.drop_index('ix_feed_events_user_created_at', table_name='feed_events')
    op.drop_index('ix_feed_events_project_created_at', table_name='feed_events')
    op.drop_index(op.f('ix_feed_events_live_project_id'), table_name='feed_events')
    op.drop_index('ix_feed_events_created_at', table_name='feed_events')
    op.drop_table('feed_events')
    # ### end Alembic commands ###
