"""add profile extra fields

Revision ID: 508cfe264abc
Revises: bd7a395fd28f
Create Date: 2026-05-13 15:37:14.670562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '508cfe264abc'
down_revision: Union[str, Sequence[str], None] = 'bd7a395fd28f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('instagram_url', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('current_build', sa.String(length=160), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_build')
    op.drop_column('users', 'location')
    op.drop_column('users', 'instagram_url')
    # ### end Alembic commands ###
