"""asjkhdgflk

Revision ID: 54582825b0fb
Revises: 2ed7a43da1d6
Create Date: 2026-06-07 19:24:16.683563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54582825b0fb'
down_revision: Union[str, Sequence[str], None] = '2ed7a43da1d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_tickets_project_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_status'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_ticket_number'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='support_tickets')
    op.drop_table('support_tickets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_tickets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ticket_number', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('category', postgresql.ENUM('bug', 'account', 'integration', 'feature_not_working', 'other', name='ticket_category'), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('open', 'in_progress', 'waiting_on_user', 'resolved', 'closed', name='ticket_status'), server_default=sa.text("'open'::ticket_status"), autoincrement=False, nullable=False),
    sa.Column('priority', postgresql.ENUM('low', 'normal', 'high', 'urgent', name='ticket_priority'), server_default=sa.text("'normal'::ticket_priority"), autoincrement=False, nullable=False),
    sa.Column('diagnostics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('internal_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('resolved_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('support_tickets_project_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], name=op.f('support_tickets_resolved_by_user_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('support_tickets_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('support_tickets_pkey'))
    )
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_ticket_number'), 'support_tickets', ['ticket_number'], unique=True)
    op.create_index(op.f('ix_support_tickets_status'), 'support_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_support_tickets_project_id'), 'support_tickets', ['project_id'], unique=False)
    # ### end Alembic commands ###
