"""add is_draft to live projects

Revision ID: 573aa5005d5c
Revises: 18de52d74d24
Create Date: 2026-05-30 16:53:42.577622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '573aa5005d5c'
down_revision: Union[str, Sequence[str], None] = '18de52d74d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_projects', sa.Column('is_draft', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live_projects', 'is_draft')
    # ### end Alembic commands ###
