"""asdkfhjg

Revision ID: 7d63714b2ea6
Revises: 00244fc746c3
Create Date: 2026-05-20 18:21:53.864863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d63714b2ea6'
down_revision: Union[str, Sequence[str], None] = '00244fc746c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('project_comment_votes_comment_id_fkey'), 'project_comment_votes', type_='foreignkey')
    op.drop_constraint(op.f('project_comment_votes_user_id_fkey'), 'project_comment_votes', type_='foreignkey')
    op.create_foreign_key(None, 'project_comment_votes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'project_comment_votes', 'project_comments', ['comment_id'], ['id'])
    op.drop_constraint(op.f('project_comments_project_id_fkey'), 'project_comments', type_='foreignkey')
    op.drop_constraint(op.f('project_comments_user_id_fkey'), 'project_comments', type_='foreignkey')
    op.create_foreign_key(None, 'project_comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'project_comments', 'projects', ['project_id'], ['id'])
    op.drop_constraint(op.f('project_stars_project_id_fkey'), 'project_stars', type_='foreignkey')
    op.drop_constraint(op.f('project_stars_user_id_fkey'), 'project_stars', type_='foreignkey')
    op.create_foreign_key(None, 'project_stars', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'project_stars', 'projects', ['project_id'], ['id'])
    op.alter_column('projects', 'demo_video_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('projects_user_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_user_id_fkey'), 'projects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('projects', 'demo_video_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'project_stars', type_='foreignkey')
    op.drop_constraint(None, 'project_stars', type_='foreignkey')
    op.create_foreign_key(op.f('project_stars_user_id_fkey'), 'project_stars', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('project_stars_project_id_fkey'), 'project_stars', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'project_comments', type_='foreignkey')
    op.drop_constraint(None, 'project_comments', type_='foreignkey')
    op.create_foreign_key(op.f('project_comments_user_id_fkey'), 'project_comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('project_comments_project_id_fkey'), 'project_comments', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'project_comment_votes', type_='foreignkey')
    op.drop_constraint(None, 'project_comment_votes', type_='foreignkey')
    op.create_foreign_key(op.f('project_comment_votes_user_id_fkey'), 'project_comment_votes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('project_comment_votes_comment_id_fkey'), 'project_comment_votes', 'project_comments', ['comment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
