"""added follower

Revision ID: 88ad7f2d9c75
Revises: eed7a116b954
Create Date: 2026-06-08 18:58:16.048783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ad7f2d9c75'
down_revision: Union[str, Sequence[str], None] = 'eed7a116b954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_follows_follower_id'), 'follows', ['follower_id'], unique=False)
    op.create_index(op.f('ix_follows_following_id'), 'follows', ['following_id'], unique=False)
    op.create_unique_constraint('uq_follower_following', 'follows', ['follower_id', 'following_id'])
    op.drop_constraint(op.f('follows_follower_id_fkey'), 'follows', type_='foreignkey')
    op.drop_constraint(op.f('follows_following_id_fkey'), 'follows', type_='foreignkey')
    op.create_foreign_key(None, 'follows', 'users', ['follower_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'follows', 'users', ['following_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.create_foreign_key(op.f('follows_following_id_fkey'), 'follows', 'users', ['following_id'], ['id'])
    op.create_foreign_key(op.f('follows_follower_id_fkey'), 'follows', 'users', ['follower_id'], ['id'])
    op.drop_constraint('uq_follower_following', 'follows', type_='unique')
    op.drop_index(op.f('ix_follows_following_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_follower_id'), table_name='follows')
    # ### end Alembic commands ###
