"""add parent_id to project_comments

Revision ID: 8d1b81672c3e
Revises: 508cfe264abc
Create Date: 2026-05-19 13:39:26.111991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d1b81672c3e'
down_revision: Union[str, Sequence[str], None] = '508cfe264abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('upvotes_count', sa.Integer(), nullable=False),
    sa.Column('downvotes_count', sa.Integer(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['project_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_comments_parent_id', 'project_comments', ['parent_id'], unique=False)
    op.create_index('ix_project_comments_project_id', 'project_comments', ['project_id'], unique=False)
    op.create_table('project_comment_votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('vote_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("vote_type IN ('up', 'down')", name='check_vote_type'),
    sa.ForeignKeyConstraint(['comment_id'], ['project_comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'comment_id', name='unique_user_comment_vote')
    )
    op.create_unique_constraint('unique_project_star', 'project_stars', ['user_id', 'project_id'])
    op.add_column('projects', sa.Column('gallery_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('projects', sa.Column('github_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('projects', sa.Column('comments_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'comments_count')
    op.drop_column('projects', 'github_data')
    op.drop_column('projects', 'gallery_urls')
    op.drop_constraint('unique_project_star', 'project_stars', type_='unique')
    op.drop_table('project_comment_votes')
    op.drop_index('ix_project_comments_project_id', table_name='project_comments')
    op.drop_index('ix_project_comments_parent_id', table_name='project_comments')
    op.drop_table('project_comments')
    # ### end Alembic commands ###
