""":asjkhdgfajkshdgf

Revision ID: af8fded8d660
Revises: dce47bf7e32a
Create Date: 2026-05-23 21:05:27.275978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af8fded8d660'
down_revision: Union[str, Sequence[str], None] = 'dce47bf7e32a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_stars', sa.Column('clerk_user_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_stars', 'clerk_user_id')
    # ### end Alembic commands ###
