"""added clerk_user_id to project stars

Revision ID: dce47bf7e32a
Revises: 7d63714b2ea6
Create Date: 2026-05-23 20:39:34.678748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dce47bf7e32a'
down_revision: Union[str, Sequence[str], None] = '7d63714b2ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_stars', sa.Column('clerk_user_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_stars', 'clerk_user_id')
    # ### end Alembic commands ###
