"""changelog

Revision ID: eb5b75a57565
Revises: 88ad7f2d9c75
Create Date: 2026-06-09 10:15:05.142050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb5b75a57565'
down_revision: Union[str, Sequence[str], None] = '88ad7f2d9c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('changelogs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('changelog_type', sa.String(length=40), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_changelogs_changelog_type'), 'changelogs', ['changelog_type'], unique=False)
    op.create_index(op.f('ix_changelogs_id'), 'changelogs', ['id'], unique=False)
    op.create_index(op.f('ix_changelogs_is_published'), 'changelogs', ['is_published'], unique=False)
    op.create_index(op.f('ix_changelogs_published_at'), 'changelogs', ['published_at'], unique=False)
    op.create_index(op.f('ix_changelogs_slug'), 'changelogs', ['slug'], unique=True)
    op.create_index(op.f('ix_changelogs_title'), 'changelogs', ['title'], unique=False)
    op.create_index(op.f('ix_changelogs_version'), 'changelogs', ['version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_changelogs_version'), table_name='changelogs')
    op.drop_index(op.f('ix_changelogs_title'), table_name='changelogs')
    op.drop_index(op.f('ix_changelogs_slug'), table_name='changelogs')
    op.drop_index(op.f('ix_changelogs_published_at'), table_name='changelogs')
    op.drop_index(op.f('ix_changelogs_is_published'), table_name='changelogs')
    op.drop_index(op.f('ix_changelogs_id'), table_name='changelogs')
    op.drop_index(op.f('ix_changelogs_changelog_type'), table_name='changelogs')
    op.drop_table('changelogs')
    # ### end Alembic commands ###
