"""changelog

Revision ID: ed8a89362b40
Revises: eb5b75a57565
Create Date: 2026-06-09 11:59:57.309653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed8a89362b40'
down_revision: Union[str, Sequence[str], None] = 'eb5b75a57565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_notices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notice_type', sa.String(length=40), nullable=False),
    sa.Column('cta_label', sa.String(length=80), nullable=True),
    sa.Column('cta_href', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('show_once', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_notices_expires_at'), 'app_notices', ['expires_at'], unique=False)
    op.create_index(op.f('ix_app_notices_id'), 'app_notices', ['id'], unique=False)
    op.create_index(op.f('ix_app_notices_is_active'), 'app_notices', ['is_active'], unique=False)
    op.create_index(op.f('ix_app_notices_notice_type'), 'app_notices', ['notice_type'], unique=False)
    op.create_index(op.f('ix_app_notices_priority'), 'app_notices', ['priority'], unique=False)
    op.create_index(op.f('ix_app_notices_starts_at'), 'app_notices', ['starts_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_notices_starts_at'), table_name='app_notices')
    op.drop_index(op.f('ix_app_notices_priority'), table_name='app_notices')
    op.drop_index(op.f('ix_app_notices_notice_type'), table_name='app_notices')
    op.drop_index(op.f('ix_app_notices_is_active'), table_name='app_notices')
    op.drop_index(op.f('ix_app_notices_id'), table_name='app_notices')
    op.drop_index(op.f('ix_app_notices_expires_at'), table_name='app_notices')
    op.drop_table('app_notices')
    # ### end Alembic commands ###
